//todo: standardize enum style
export enum ActionType {
    ATTACK,
    ATTACK_CONTROLLER,
    BUILD,
    CANCEL_ACTION,
    CLAIM_CONTROLLER,
    DISMANTLE,
    DROP,
    HARVEST,
    HEAL,    
    MOVE,
    RANGED_ATTACK,
    RANGED_HEAL,
    RANGED_MASS_ATTACK,
    REPAIR,
    RESERVE_CONTROLLER,
    SIGN_CONTROLLER,
    TRANSFER,
    UPGRADE_CONTROLLER,
    WITHDRAW    
}
