declare interface global {
TASK_IDLE: string;
TASK_MOVE_TO: string;
TASK_TRANSFER: string;
TASK_WITHDRAW: string;
TASK_BUILD: string;
TASK_UPGRADE: string;
TASK_REPAIR: string;
TASK_ATTACK: string;
TASK_RESERVE: string;

OPERATION_LIGHT_UPGRADE: string;
OPERATION_HEAVY_UPGRADE: string;
OPERATION_HARVEST: string;
OPERATION_REMOTE_HARVEST_SCOUT: string;
OPERATION_REMOTE_HARVEST: string;
OPERATION_ENERGY_TRANSPORT: string;
OPERATION_EXTRACTION: string;
OPERATION_EXTENSION_FILL: string;
OPERATION_STORAGE_CONSTRUCTION: string;
OPERATION_TOWER_CONSTRUCTION: string;
OPERATION_HARVEST_INFRASTRUCTURE: string;
OPERATION_EXTENSION_CONSTRUCTION: string;
OPERATION_CONTROLLER_INFRASTRUCTURE: string;
OPERATION_HARVEST_LINK_CONSTRUCTION: string;
OPERATION_UPGRADE_LINK_CONSTRUCTION: string;
OPERATION_EXTENSION_LINK_CONSTRUCTION: string;
OPERATION_ROOM_DEFENSE: string;
OPERATION_LAB_CONSTRUCTION: string;
OPERATION_EXTRACTOR_CONSTRUCTION: string;
OPERATION_TERMINAL_CONSTRUCTION: string;
OPERATION_OBSERVER_CONSTRUCTION: string;
OPERATION_STORAGE_LINK_CONSTRUCTION: string;
OPERATION_WALL_CONSTRUCTION: string;
OPERATION_ROAD_CONSTRUCTION: string;
OPERATION_SPAWN_CONSTRUCTION: string;

PROGRESS_STANDARD: string;

PLAN_INFRASTRUCTURE: string;
PLAN_ECONOMY: string;
PLAN_REMOTE_MINING: string;
PLAN_ROAD: string;
PLAN_DEFENSE: string;

CREEP_CONTROLLER_HARVESTER: string;
CREEP_CONTROLLER_HARVEST_INFRASTRUCTURE_BUILDER: string;
CREEP_CONTROLLER_LIGHT_UPGRADER: string;
CREEP_CONTROLLER_BUILDER: string;
CREEP_CONTROLLER_HAULER: string;
CREEP_CONTROLLER_UPGRADER: string;
CREEP_CONTROLLER_REMOTE_HAULER: string;
CREEP_CONTROLLER_REMOTE_HARVESTER: string;
CREEP_CONTROLLER_EXTRACTOR: string;
CREEP_CONTROLLER_FILLER: string;
CREEP_CONTROLLER_CHEMIST: string;
CREEP_CONTROLLER_MASON: string;
CREEP_CONTROLLER_REPAIR: string;
CREEP_CONTROLLER_DEFENDER: string;

BODY_LIGHT_WORKER: string;
BODY_HEAVY_HARVESTER: string;
BODY_HEAVY_UPGRADER: string;
BODY_HAULER: string;
BODY_WARRIOR: string;
BODY_SCOUT: string;
BODY_DEFENDER: string;

}
