declare interface global {
    MONITOR_COLONY_DEFENSE: string;
    MONITOR_ECONOMY_OPERATION: string;
    MONITOR_INFRASTRUCTURE_OPERATION: string;
    MONITOR_COLONY_RESOURCES: string;
    MONITOR_EXCHANGE: string;
    MONITOR_REMOTE_MINING: string;

    MONITOR_PROVIDER_COLONY_STANDARD: string;
    MONITOR_PROVIDER_EMPIRE_STANDARD: string;

    CAMPAIGN_CLAIM_COLONY: string;

    FLAG_CAMPAIGN_CLAIM_COLONY: string;

    OPERATION_LIGHT_UPGRADE: string;
    OPERATION_HEAVY_UPGRADE: string;
    OPERATION_HARVEST: string;
    OPERATION_REMOTE_HARVEST_SCOUT: string;
    OPERATION_REMOTE_HARVEST: string;
    OPERATION_ENERGY_TRANSPORT: string;
    OPERATION_EXTRACTION: string;
    OPERATION_EXTENSION_FILL: string;
    OPERATION_STORAGE_CONSTRUCTION: string;
    OPERATION_TOWER_CONSTRUCTION: string;
    OPERATION_HARVEST_INFRASTRUCTURE: string;
    OPERATION_EXTENSION_CONSTRUCTION: string;
    OPERATION_CONTROLLER_INFRASTRUCTURE: string;
    OPERATION_HARVEST_LINK_CONSTRUCTION: string;
    OPERATION_UPGRADE_LINK_CONSTRUCTION: string;
    OPERATION_EXTENSION_LINK_CONSTRUCTION: string;
    OPERATION_ROOM_DEFENSE: string;
    OPERATION_LAB_CONSTRUCTION: string;
    OPERATION_EXTRACTOR_CONSTRUCTION: string;
    OPERATION_TERMINAL_CONSTRUCTION: string;
    OPERATION_OBSERVER_CONSTRUCTION: string;
    OPERATION_STORAGE_LINK_CONSTRUCTION: string;
    OPERATION_WALL_CONSTRUCTION: string;
    OPERATION_ROAD_CONSTRUCTION: string;
    OPERATION_SPAWN_CONSTRUCTION: string;
    OPERATION_REPLACE_ORIGINAL_SPAWN: string;
    OPERATION_ROOM_SCOUT: string;
    OPERATION_NEW_SPAWN_CONSTRUCTION: string;
    OPERATION_RESERVATION: string;
    OPERATION_DISMANTLE: string;
    OPERATION_LOOT: string;
    OPERATION_CLAIM_ROOM: string;
    OPERATION_SUPPLY: string;
    OPERATION_MAP_SCOUT: string;

    FLAG_OPERATION_DISMANTLE: string;
    FLAG_OPERATION_LOOT: string;

    UNIT_CONTROLLER_RALLY: string;
    UNIT_CONTROLLER_MOVE_TO: string;
    UNIT_CONTROLLER_ROOM_DEFENSE: string;

    CREEP_CONTROLLER_HARVESTER: string;
    CREEP_CONTROLLER_HARVEST_INFRASTRUCTURE_BUILDER: string;
    CREEP_CONTROLLER_LIGHT_UPGRADER: string;
    CREEP_CONTROLLER_BUILDER: string;
    CREEP_CONTROLLER_HAULER: string;
    CREEP_CONTROLLER_UPGRADER: string;
    CREEP_CONTROLLER_REMOTE_HAULER: string;
    CREEP_CONTROLLER_REMOTE_HARVESTER: string;
    CREEP_CONTROLLER_EXTRACTOR: string;
    CREEP_CONTROLLER_FILLER: string;
    CREEP_CONTROLLER_CHEMIST: string;
    CREEP_CONTROLLER_MASON: string;
    CREEP_CONTROLLER_REPAIR: string;
    CREEP_CONTROLLER_DEFENDER: string;
    CREEP_CONTROLLER_CLAIM: string;
    CREEP_CONTROLLER_SCOUT: string;
    CREEP_CONTROLLER_RESERVE: string;
    CREEP_CONTROLLER_WARRIOR: string;
    CREEP_CONTROLLER_DISMANTLER: string;
    CREEP_CONTROLLER_WITHDRAW: string;
    CREEP_CONTROLLER_TRANSFER: string;
    CREEP_CONTROLLER_HARVEST_BUILDER: string;
    CREEP_CONTROLLER_SUPPLY: string;
    CREEP_CONTROLLER_HEAL_TARGET: string;
    CREEP_CONTROLLER_WARRIOR_ATTACK_TARGET: string;

    TASK_IDLE: string;
    TASK_MOVE_TO: string;
    TASK_TRANSFER: string;
    TASK_WITHDRAW: string;
    TASK_BUILD: string;
    TASK_UPGRADE: string;
    TASK_REPAIR: string;
    TASK_ATTACK: string;
    TASK_RESERVE: string;
    TASK_CLAIM: string;
    TASK_HARVEST: string;
    TASK_PICKUP_ENERGY: string;
    TASK_DISMANTLE: string;
    TASK_HEAL: string;

    BODY_LIGHT_WORKER: string;
    BODY_HEAVY_HARVESTER: string;
    BODY_HEAVY_UPGRADER: string;
    BODY_HAULER: string;
    BODY_WARRIOR: string;
    BODY_SCOUT: string;
    BODY_DEFENDER: string;
    BODY_CLAIMER: string;
    BODY_RANGER: string;
    BODY_HEALER: string;
    BODY_HOPLITE: string;
    BODY_SHIELD: string;
    BODY_DISMANTLER: string;

}
